### ISSUE TITLE
Pine64/Pine64 Plus

### ISSUE THREAD

**Issue by SethBarberee** [enunes/buildroot-external-lima#4]
Hi,

I was wondering if you would accept a PR for Pine64/Pine64 Plus support. It uses a MALI-400 GPU too so it benefits from the lima work. I am working on the support as you see this.

**Comment by enunes** [comment]
Sure, just make sure that it is like the existing ones if you submit a new one. Since the A64 supports armv8 it might be a bit different, but please make it equivalent to the others at least in terms of selected options and user space packages.
