### ISSUE TITLE
not merging config 

### ISSUE THREAD

**Issue by Lipton2kirov** [enunes/buildroot-external-lima#5]
Hello,
an error occurs during configuration merge:
../buildroot/support/kconfig/merge_config.sh .config ../buildroot-external-lima/configs/lima-config.frag
Using .config as base
Merging ../buildroot-external-lima/configs/lima-config.frag
umask 0022 && make -C /home/lipton/tmpl/lima/buildroot O=/home/lipton/tmpl/lima/output/. alldefconfig
  GEN     /home/lipton/tmpl/lima/output/Makefile
*** Can't read seed configuration "./.tmp.config.eZvc76oxaM"!
Makefile:926: recipe execution error for goal «alldefconfig»
make[1]: *** [alldefconfig] Error 1
Makefile:16: recipe execution error for goal  «_all»
make: *** [_all] Error 2

**Comment by enunes** [comment]
Hello,
you are right, something changed recently on Buildroot that broke this. Looks like `merge_config.sh` is not working properly with out-of-tree builds. I can report this to the Buildroot mailing list. For now, I see two possible workarounds:
1) use a previous Buildroot release, from before the kconfig changes, looks like `2018.08` works fine. or,
2) run `merge_config.sh` from the Buildroot tree, something like this:
```
cd buildroot
support/kconfig/merge_config.sh -O ../output ../output/.config ../buildroot-external-lima/configs/lima-config.frag
```

**Comment by enunes** [comment]
I reported it to the mailing list some days ago and a fix is already on the way:
http://lists.busybox.net/pipermail/buildroot/2018-October/234431.html
http://lists.busybox.net/pipermail/buildroot/2018-October/234434.html

**Comment by enunes** [comment]
The fixes have been merged, so I'm closing this issue. Thanks for reporting.
